# Generated by Django 5.2.7 on 2025-11-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio_vidafit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('yoga', 'Yoga'), ('natacion', 'Natación'), ('musculacion', 'Musculación')], max_length=20, null=True),
        ),
    ]
