# Generated by Django 5.2.7 on 2025-10-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio_vidafit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
