# Generated by Django 5.2.7 on 2025-10-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio_vidafit', '0003_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
