# Generated by Django 5.2.7 on 2025-10-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio_vidafit', '0004_profesional_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
    ]
