# Generated by Django 5.2.7 on 2025-11-04 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('altura', models.IntegerField(unique=True)),
                ('codigo', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
            ],
        ),
    ]
