# Generated by Django 5.2.7 on 2025-11-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sedes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='altura',
            field=models.IntegerField(unique=True),
        ),
    ]
