# Generated by Django 5.2.7 on 2025-11-04 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sedes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
