# Generated by Django 5.2.7 on 2025-11-05 20:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Sube una imagen del artículo', null=True, upload_to='articulos/')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
