# Generated by Django 5.2.7 on 2025-11-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Sube una imagen del artículo', null=True, upload_to='articulos/'),
        ),
    ]
